"""new migration

Revision ID: cdf70cfca8df
Revises: 
Create Date: 2026-08-29 21:26:00.500959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf70cfca8df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loja',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NOME', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('analista',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IdLoja', sa.Integer(), nullable=False),
    sa.Column('NOME', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['IdLoja'], ['loja.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('consultor',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IdLoja', sa.Integer(), nullable=False),
    sa.Column('NOME', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['IdLoja'], ['loja.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('esperados',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IdLoja', sa.Integer(), nullable=False),
    sa.Column('PRODUTO', sa.String(), nullable=False),
    sa.Column('QUANTIDADE', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['IdLoja'], ['loja.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('ofertas',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IdLoja', sa.Integer(), nullable=True),
    sa.Column('PRODUTO', sa.String(), nullable=False),
    sa.Column('PRECO', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['IdLoja'], ['loja.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('usuario',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IdLoja', sa.Integer(), nullable=False),
    sa.Column('LOGIN', sa.String(), nullable=False),
    sa.Column('SENHA', sa.String(), nullable=False),
    sa.Column('CARGO', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['IdLoja'], ['loja.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('cadastro_backlog',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IdLoja', sa.Integer(), nullable=False),
    sa.Column('IdConsultor', sa.Integer(), nullable=False),
    sa.Column('ORDEM', sa.String(), nullable=False),
    sa.Column('CRIACAO', sa.String(), nullable=False),
    sa.Column('INSTALACAO', sa.String(), nullable=False),
    sa.Column('HORA', sa.String(), nullable=False),
    sa.Column('STATUS', sa.String(), nullable=False),
    sa.Column('OBSERVACAO', sa.String(), server_default='Sem observação', nullable=True),
    sa.ForeignKeyConstraint(['IdConsultor'], ['consultor.ID'], ),
    sa.ForeignKeyConstraint(['IdLoja'], ['loja.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('acompanhamento',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('IdLoja', sa.Integer(), nullable=False),
    sa.Column('IdConsultor', sa.Integer(), nullable=False),
    sa.Column('IdBacklog', sa.Integer(), nullable=False),
    sa.Column('DATA', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['IdBacklog'], ['cadastro_backlog.ID'], ),
    sa.ForeignKeyConstraint(['IdConsultor'], ['consultor.ID'], ),
    sa.ForeignKeyConstraint(['IdLoja'], ['loja.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acompanhamento')
    op.drop_table('cadastro_backlog')
    op.drop_table('usuario')
    op.drop_table('ofertas')
    op.drop_table('esperados')
    op.drop_table('consultor')
    op.drop_table('analista')
    op.drop_table('loja')
    # ### end Alembic commands ###
